### ISSUE TITLE
:lady_beetle: [BUG] Setting group message title crashes the app

### ISSUE THREAD

**Issue by octoshrimpy** [octoshrimpy/quik#13]
### EXPECTED
convo changes title

### OBSERVATIONS
app crashes

---
https://github.com/moezbhatti/qksms/issues/1924

**Comment by navyjosh** [comment]
Hello, why was this closed? I am still experiencing this issue.

**Comment by navyjosh** [comment]
Confirmed this is happening:

OS: GrapheneOS


Crash Trace:
```
```
type: crash
osVersion: google/oriole/oriole:14/UQ1A.240205.002/2024020500:user/release-keys
package: dev.octoshrimpy.quik:2221
process: dev.octoshrimpy.quik
processUptime: 22023 + 94 ms
installer: com.android.packageinstaller

io.reactivex.exceptions.OnErrorNotImplementedException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
Caused by: io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
	at dev.octoshrimpy.quik.feature.conversationinfo.ConversationInfoPresenter.bindIntents(ConversationInfoPresenter.kt:150)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at io.realm.BaseRealm.checkAllowWritesOnUiThread(BaseRealm.java:553)
	at io.realm.Realm.executeTransaction(Realm.java:1629)
	at dev.octoshrimpy.quik.repository.ConversationRepositoryImpl.setConversationName(ConversationRepositoryImpl.kt:123)
	at dev.octoshrimpy.quik.feature.conversationinfo.ConversationInfoPresenter$bindIntents$$inlined$withLatestFrom$2.apply(Observables.kt:192)
	at io.reactivex.internal.operators.observable.ObservableWithLatestFrom$WithLatestFromObserver.onNext(ObservableWithLatestFrom.java:76)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
	at dev.octoshrimpy.quik.feature.conversationinfo.ConversationInfoController$nameDialog$2$1.invoke(ConversationInfoController.kt:53)
	at dev.octoshrimpy.quik.feature.conversationinfo.ConversationInfoController$nameDialog$2$1.invoke(ConversationInfoController.kt:53)
	at dev.octoshrimpy.quik.common.widget.TextInputDialog._init_$lambda$2(TextInputDialog.kt:39)
	at dev.octoshrimpy.quik.common.widget.TextInputDialog.$r8$lambda$eFPQCCDNIvFzySAddZAKh335qyc(Unknown Source:0)
	at dev.octoshrimpy.quik.common.widget.TextInputDialog$$ExternalSyntheticLambda2.onClick(Unknown Source:4)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```


```

**Comment by octoshrimpy** [comment]
fixed by #58 !
