### ISSUE TITLE
:lady_beetle: [BUG]Crash when I enter blocked numbers

### ISSUE THREAD

**Issue by anenasa** [octoshrimpy/quik#131]
**Describe the bug**
QUIK crashes when I enter blocked numbers. Here is logcat:
```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at com.uber.rxdogtag.DogTagObserver.lambda$onNext$3$com-uber-rxdogtag-DogTagObserver(DogTagObserver.java:56)
	at com.uber.rxdogtag.DogTagObserver$$ExternalSyntheticLambda5.run(Unknown Source:4)
	at com.uber.rxdogtag.RxDogTag.guardedDelegateCall(RxDogTag.java:221)
	at com.uber.rxdogtag.DogTagObserver.onNext(DogTagObserver.java:56)
	at com.uber.autodispose.HalfSerializer.onNext(HalfSerializer.java:121)
	at com.uber.autodispose.AutoDisposingObserverImpl.onNext(AutoDisposingObserverImpl.java:85)
	at com.uber.rxdogtag.DogTagObserver.lambda$onNext$3$com-uber-rxdogtag-DogTagObserver(DogTagObserver.java:56)
	at com.uber.rxdogtag.DogTagObserver$$ExternalSyntheticLambda5.run(Unknown Source:4)
	at com.uber.rxdogtag.RxDogTag.guardedDelegateCall(RxDogTag.java:221)
	at com.uber.rxdogtag.DogTagObserver.onNext(DogTagObserver.java:56)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
	at dev.octoshrimpy.quik.feature.blocking.numbers.BlockedNumbersController.showAddDialog$lambda$0(BlockedNumbersController.kt:84)
	at dev.octoshrimpy.quik.feature.blocking.numbers.BlockedNumbersController.$r8$lambda$O7oMuhkDdxQGUzVm3ggIcStgurU(Unknown Source:0)
	at dev.octoshrimpy.quik.feature.blocking.numbers.BlockedNumbersController$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: io.realm.exceptions.RealmException: Running transactions on the UI thread has been disabled. It can be enabled by setting 'RealmConfiguration.Builder.allowWritesOnUiThread(true)'.
	at dev.octoshrimpy.quik.feature.blocking.numbers.BlockedNumbersPresenter.bindIntents(BlockedNumbersPresenter.kt:59)
	at [[ ↑↑ Inferred subscribe point ↑↑ ]].(:0)
	at [[ Originating callback: onNext ]].(:0)
	at [[ ↓↓ Original trace ↓↓ ]].(:0)
	at io.realm.BaseRealm.checkAllowWritesOnUiThread(BaseRealm.java:553)
	at io.realm.Realm.executeTransaction(Realm.java:1629)
	at dev.octoshrimpy.quik.repository.BlockingRepositoryImpl.blockNumber(BlockingRepositoryImpl.kt:44)
	at dev.octoshrimpy.quik.feature.blocking.numbers.BlockedNumbersPresenter$bindIntents$4.invoke(BlockedNumbersPresenter.kt:59)
	at dev.octoshrimpy.quik.feature.blocking.numbers.BlockedNumbersPresenter$bindIntents$4.invoke(BlockedNumbersPresenter.kt:59)
	at dev.octoshrimpy.quik.feature.blocking.numbers.BlockedNumbersPresenter.bindIntents$lambda$3(BlockedNumbersPresenter.kt:59)
```

**To Reproduce**
1. Open navigation drawer
2. Click on 'Blocking'
3. Click on 'Blocked numbers'
4. Click on '+'
5. Enter phone number
6. Click on 'BLOCK'

**Expected behavior**
Blocked number added

**Smartphone (please complete the following information):**
 - Device: POCO X4 Pro
 - OS: Android 14, crdroid
 - App Version: 4.0.7 (also tested latest commit on master branch)

**Screenshots**

**Additional context**

**Comment by BobSquarePants** [comment]
I got the same.
quik version: 4.0.7

tried phone number format: `+123456789` `00123456789` no matter the format it always crash

**Comment by gavine99** [comment]
pr https://github.com/octoshrimpy/quik/pull/233 should fix this issue. please test using the next release

**Comment by octoshrimpy** [comment]
not closing until confirmed solved.

**Comment by anenasa** [comment]
In v4.0.9-beta quik no longer crashes for me.
