### ISSUE TITLE
:lady_beetle: [BUG] Crash on open under Android 15

### ISSUE THREAD

**Issue by Crypt0K33p3r** [octoshrimpy/quik#177]
**Describe the bug**
QUIK crashes on open under the latest version of Graphene OS, which is now running Android 15

**To Reproduce**
1. Open the app

**Expected behavior**
App will instantly crash. If you receive a text, you can open it and reply without issues. If you press the back arrow to return to the chat list, it will again crash.

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: latest Graphene OS, Android 15
 - App Version: v4.0.8-alpha

**Screenshots**

**Additional context**
```
type: crash
osVersion: google/cheetah/cheetah:15/AP3A.241005.015/2024103100:user/release-keys
flags: dev options enabled
package: dev.octoshrimpy.quik:2225, targetSdk 33
process: dev.octoshrimpy.quik
processUptime: 163 + 247 ms
installer: dev.imranr.obtainium

java.lang.RuntimeException: Failed to find the generated JsonAdapter class for class dev.octoshrimpy.quik.manager.ChangelogManagerImpl$Changeset
	at com.squareup.moshi.internal.Util.generatedAdapter(Unknown Source:231)
	at com.squareup.moshi.StandardJsonAdapters$1.create(Unknown Source:145)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(Unknown Source:6)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(Unknown Source:35)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at com.squareup.moshi.Moshi.adapter(SourceFile:0)
	at dev.octoshrimpy.quik.manager.ChangelogManagerImpl.getChangelog(Unknown Source:16)
	at dev.octoshrimpy.quik.feature.main.MainViewModel$bindView$18.invokeSuspend(Unknown Source:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:95)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.ClassNotFoundException: dev.octoshrimpy.quik.manager.ChangelogManagerImpl_ChangesetJsonAdapter
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at com.squareup.moshi.internal.Util.generatedAdapter(Unknown Source:52)
	... 23 more
Caused by: java.lang.ClassNotFoundException: dev.octoshrimpy.quik.manager.ChangelogManagerImpl_ChangesetJsonAdapter
	... 26 more

```

**Comment by octoshrimpy** [comment]
has been fixed with either APK from this pre-release: 
https://github.com/octoshrimpy/quik/releases/tag/v4.0.8-beta
